import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { cn } from "../lib/cn-merge"
import { Header } from "./components/Header"
import { Toaster } from "./components/Toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-gray-950")}>
        <div className="h-full min-h-screen w-screen">
          <Header />
          {children}
        </div>
      </body>
      <Toaster />
    </html>
  )
}
